### Exercise 9.8 - GET Request to ping endpoint
## Expect a console.log and a pong response
GET http://localhost:3000/api/ping

### Exercise 9.10 - GET Request to diagnoses endpoint
## Expect a json with all diagnoses
GET http://localhost:3000/api/diagnoses