### Exercise 9.8 - GET Request to ping endpoint
## Expect a console.log and a pong response
GET http://localhost:3000/api/ping

### Exercise 9.10 - GET Request to diagnoses endpoint
## Expect a json with all diagnoses
GET http://localhost:3000/api/diagnoses

### Exercise 9.11 - GET Request to patients endpoint
## Expect a json with all patients, excluding the ssn property
GET http://localhost:3000/api/patients

### Exercise 9.12 - POST Request to patients endpoint
## Expect a json with the new patient with id, excluding the ssn property
POST http://localhost:3000/api/patients
Content-Type: application/json

{
  "name": "Juma Marruá",
  "dateOfBirth": "1995-07-26",
  "ssn": "153153-315A",
  "gender": "female",
  "occupation": "Caipira"
}

### Exercise 9.16 - GET Request to a single patient endpoint (by id)
## Expect a json with the all the information for one patient, including the array of patient entries
GET http://localhost:3000/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667